<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerXNKlmIJ\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerXNKlmIJ/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerXNKlmIJ.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerXNKlmIJ\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerXNKlmIJ\App_KernelDevDebugContainer([
    'container.build_hash' => 'XNKlmIJ',
    'container.build_id' => 'dd024ed1',
    'container.build_time' => 1663674667,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerXNKlmIJ');
